YawReferences: [3]
FrontReferences: [180]
SideReferences: [320]
AltReferences: [0.70]
YawKp: 0.0015
YawKi: 0.001
YawKd: 0.0
YawIntegralWindupGuard: 1
FrontKp: 0.02
FrontKi: 0.02
FrontKd: 0.2
FrontIntegralWindupGuard: 0.5
SideKp: 0.05
SideKi: 0.05
SideKd: 0.2
SideIntegralWindupGuard: 0.5
AltKp: 0.5
AltKi: 0.0
AltKd: 0.0
AltIntegralWindupGuard: 1
PidDeltaT: 0.033
ObjLoc_ImgW: 640
ObjLoc_ImgH: 360
ObjLoc_SideThr: 30
ObjLoc_FrontThr: 30
ObjLoc_AltThr: 0.01
ObjLoc_YawThr: 5.0
ObjLoc_ScoreThr: 0.5
PoseNet_FilterSize: 1
GazeboModelID: 2
